title: From JavaScript to Python
author: jdegand
email: not necessary
description: > # this means to ignore newlines until "baseurl:"
  JavaScript to Python - What to do when most of your loops go missing

# social links 
twitter_username: will never join
github_username:  jdegand

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
